#%RAML 1.0 Library
uses:
  core: coreLib.raml
types:
  typeName:
    type: string
    (core.enumValues): "['object','string','number','boolean','date','array'].concat(Object.keys(context.types))"
  Type:
    (core.icon): "https://maxcdn.icons8.com/Color/PNG/24/Network/connection_status_on-24.png"
    properties:
      description?: core.markdown
      type:
         type: typeName
         default: object
      item?:
        displayName: Component type
        type: typeName
        (core.visibleWhen): $.type=='array'
        (core.requiredWhen): $.type=='array'
      pattern?:
        type: string
        (core.visibleWhen): $.type=='string'
      minLength?:
          type: integer
          (core.visibleWhen): $.type=='string'
      maxLength?:
          type: integer
          (core.visibleWhen): $.type=='string'
      minimum?:
          type: number
          (core.visibleWhen): $.type=='number'
      maximum?:
          type: number
          (core.visibleWhen): $.type=='number'
      properties?:
        properties:
          //: Property
        (core.visibleWhen): $.type=='object'
  Property:
      type: Type
      properties:
        required: boolean
        type:
          type: typeName
          default: string
  Library:
    properties:
      name?: string
      types:
        properties:
          //: Type
