#%RAML 1.0
title: Github
baseUri: https://api.github.com/
mediaType: application/json
uses:
  core: coreLib.raml
  ght: githubTypes.raml
types:
   Comment:
     type: ght.Comment
     (core.label): "${user.login} ${created_at} ${body}"
     (core.icon): user.avatar_url
     (core.htmlLabel): true
   Issue:
     type: ght.Issue
     (core.labelDecorators):
       opened:
         when: $.state=='opened'
         details: "${number} opened ${created_at} by ${user.login}"
       closed:
         when: $.state=='closed'
         details: "by ${user.login} closed at"
       comments_count:
         when: $.comments
         text+: "<img src='https://maxcdn.icons8.com/Color/PNG/24/Business/comments-24.png'>${comments}"
       labels:
         text+: {$.labels}

resourceTypes:
  list:
    get:
      displayName: <<resourcePathName | !uppercamelcase>>
      (core.list):
      (core.basicPaging): { page: page}
      responses:
        200:
          body: <<ItemType>>[]
securitySchemes:
  basic:
    type: Basic Authentication
securedBy: basic
/repos/{owner}/{repo}:
  /issues:
    get:
      displayName: Issues
      (core.errorMessageIn): message
      (core.basicPaging): { page: page}
      (core.representation): list
      (core.uifeatures):
        search: true
        grouping: true
        initialOrdering: updated_at
        listStyle:
          details: small
      queryParameters:
        state:
            enum: [open, closed, all]
            default: open
            displayName: Issue State
            (core.filter):
               noFilterValue: all
        sort:
          enum: [comments, created, updated]
          default: created
          displayName: Order by
          (core.ordering):
            created: created_at
            updated: updated_at
        page: integer
      responses:
        200:
          body:
              type: Issue[]
    /{issueNum}:
      uriParameters:
        issueNum:
          type: integer
          (core.reference): ght.Issue.number
      /comments:
          (core.memberCollection): ght.Issue
          (core.visibleWhen): $.comments
          type:  { list: {ItemType : Comment } }
          (core.columns): [updated_at, body ]
          (core.representation): list-only
