#%RAML 1.0
baseUri: https://launchlibrary.net/1.2/
title: Launch Library
uses:
  core: coreLib.raml
types:
  Base:
    properties:
      name: string
      wikiURL?: core.htmlUrl
      mapURL?: core.htmlUrl
  Pad: Base
  Agency: Base
  Location:
    properties:
      pads:
        (core.representation): elements
        type: Pad[]
  Mission:
    type: Base
    properties:
      description?: string
  Rocket:
    type: Base
    properties:
      imageURL?: core.imageUrl
    (core.detailsTemplate): !include rocketlayout.html
  Launch:
    (core.representation): inline
    properties:
      net: datetime
      name: string
      location?: Location
      rocket?: Rocket
      status: number
      vidURLs:
        type: core.url[]
        displayName: Videos
        (core.representation): elements
      missions?:
        (core.representation): elements
        type: Mission[]
    (core.icon): "https://maxcdn.icons8.com/Color/PNG/24/Transport/rocket-24.png"
mediaType: application/json
/launch:
  (core.columns): [name, net]
  (core.parametersLayout):
        allowConfiguration: true
        contributeToContextMenu: true
  (core.basicPaging):
    total: total
    results: launches
    offset: offset
  get:
    displayName: Launches
    queryParameters:
      offset: number
      startdate:
        type: date-only
        default: 2015-01-01
      enddate: date-only
      mode: string
    responses:
      200:
        body:
          properties:
            launches: Launch[]
            offset: number
            count: number
            total: number
